#
Lang: en
Defaults:
  Initial-time: 86400
  Ban-duration: 86400
  Kill-cooldown: 300
  Player-on-death-penalty: 300
  Item:
    Material: DRAGON_BREATH
    Name: "&5Breath of the time"
    Lore:
      - "&7Adds {seconds} seconds of life"
    Glow-effect: true

Rewards:
  Entities:
    PLAYER: 300
    ENDER_DRAGON: 1800
    WARDEN: 1200
    ZOMBIE: 60 #Add as many entities as you want

Database:
  type: "h2" # Options: h2 (local), mysql, sqlite, postgresql
  host: "localhost"
  port: 3306
  database_name: "deathtimer"
  username: "root"
  password: "password"
  poolsize: 10
  connectionTimeOut: 3000
Messages:
  Time-left: "&eTime left: &6{timeleft}"
  Time-alive: "&eTime alive: &6{timelive}"
  Banned: "&cYou died! Reviving in &4{time} &cseconds"