name: DeathTime
version: '1.0.0'
main: net.ezplace.deathTime.DeathTime
api-version: '1.20'
author: andrewYerNau
commands:
  deathtime:
    aliases: [dt]
    usage: "/dt help for more information"
permissions:
  deathtime.item.use:
    default: true
  deathtime.command.admin:
    default: op