name: DeathTime
version: 'Beta 0.1.1'
main: net.ezplace.deathTime.DeathTime
api-version: '1.20'
depend: []
softdepend: [PlaceholderAPI]
author: andrewYerNau
commands:
  deathtime:
    aliases: [dt]
    usage: "/dt help for more information"
permissions:
  deathtime.item.use:
    default: true
  deathtime.command.admin:
    default: op
  deathtime.bypass:
    default: op